### ISSUE TITLE
Sentry bot bug

### ISSUE THREAD

**Issue by HitoryDensetsu** [Dinorush/ExtraToolCustomization#1]
Dont know where is the conflict. After downloading this mod - bot sentry stop dealing any damage, can be fixed by "repick" sentry for bot (from sniper to burst and then back to sniper), but this helps only for one run, in second run sentry doesnt deal any damage again, until "repick" sentry for bot. Players sentry works fine.

**Comment by Dinorush** [comment]
Fixed by 5ec6666cf8c04714ddf3992aa1a50794a92f8b5d.
